// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	bridgesync "github.com/agglayer/aggkit/bridgesync"
	common "github.com/ethereum/go-ethereum/common"

	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/tree/types"
)

// Bridger is an autogenerated mock type for the Bridger type
type Bridger struct {
	mock.Mock
}

type Bridger_Expecter struct {
	mock *mock.Mock
}

func (_m *Bridger) EXPECT() *Bridger_Expecter {
	return &Bridger_Expecter{mock: &_m.Mock}
}

// GetBridgesPaged provides a mock function with given fields: ctx, pageNumber, pageSize, depositCount, networkIDs, fromAddress
func (_m *Bridger) GetBridgesPaged(ctx context.Context, pageNumber uint32, pageSize uint32, depositCount *uint64, networkIDs []uint32, fromAddress string) ([]*bridgesync.Bridge, int, error) {
	ret := _m.Called(ctx, pageNumber, pageSize, depositCount, networkIDs, fromAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetBridgesPaged")
	}

	var r0 []*bridgesync.Bridge
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, *uint64, []uint32, string) ([]*bridgesync.Bridge, int, error)); ok {
		return rf(ctx, pageNumber, pageSize, depositCount, networkIDs, fromAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, *uint64, []uint32, string) []*bridgesync.Bridge); ok {
		r0 = rf(ctx, pageNumber, pageSize, depositCount, networkIDs, fromAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bridgesync.Bridge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, *uint64, []uint32, string) int); ok {
		r1 = rf(ctx, pageNumber, pageSize, depositCount, networkIDs, fromAddress)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32, *uint64, []uint32, string) error); ok {
		r2 = rf(ctx, pageNumber, pageSize, depositCount, networkIDs, fromAddress)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Bridger_GetBridgesPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgesPaged'
type Bridger_GetBridgesPaged_Call struct {
	*mock.Call
}

// GetBridgesPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - pageNumber uint32
//   - pageSize uint32
//   - depositCount *uint64
//   - networkIDs []uint32
//   - fromAddress string
func (_e *Bridger_Expecter) GetBridgesPaged(ctx interface{}, pageNumber interface{}, pageSize interface{}, depositCount interface{}, networkIDs interface{}, fromAddress interface{}) *Bridger_GetBridgesPaged_Call {
	return &Bridger_GetBridgesPaged_Call{Call: _e.mock.On("GetBridgesPaged", ctx, pageNumber, pageSize, depositCount, networkIDs, fromAddress)}
}

func (_c *Bridger_GetBridgesPaged_Call) Run(run func(ctx context.Context, pageNumber uint32, pageSize uint32, depositCount *uint64, networkIDs []uint32, fromAddress string)) *Bridger_GetBridgesPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(*uint64), args[4].([]uint32), args[5].(string))
	})
	return _c
}

func (_c *Bridger_GetBridgesPaged_Call) Return(_a0 []*bridgesync.Bridge, _a1 int, _a2 error) *Bridger_GetBridgesPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Bridger_GetBridgesPaged_Call) RunAndReturn(run func(context.Context, uint32, uint32, *uint64, []uint32, string) ([]*bridgesync.Bridge, int, error)) *Bridger_GetBridgesPaged_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaimsPaged provides a mock function with given fields: ctx, page, pageSize, networkIDs, fromAddress
func (_m *Bridger) GetClaimsPaged(ctx context.Context, page uint32, pageSize uint32, networkIDs []uint32, fromAddress string) ([]*bridgesync.Claim, int, error) {
	ret := _m.Called(ctx, page, pageSize, networkIDs, fromAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimsPaged")
	}

	var r0 []*bridgesync.Claim
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, []uint32, string) ([]*bridgesync.Claim, int, error)); ok {
		return rf(ctx, page, pageSize, networkIDs, fromAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, []uint32, string) []*bridgesync.Claim); ok {
		r0 = rf(ctx, page, pageSize, networkIDs, fromAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bridgesync.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, []uint32, string) int); ok {
		r1 = rf(ctx, page, pageSize, networkIDs, fromAddress)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32, []uint32, string) error); ok {
		r2 = rf(ctx, page, pageSize, networkIDs, fromAddress)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Bridger_GetClaimsPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimsPaged'
type Bridger_GetClaimsPaged_Call struct {
	*mock.Call
}

// GetClaimsPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint32
//   - pageSize uint32
//   - networkIDs []uint32
//   - fromAddress string
func (_e *Bridger_Expecter) GetClaimsPaged(ctx interface{}, page interface{}, pageSize interface{}, networkIDs interface{}, fromAddress interface{}) *Bridger_GetClaimsPaged_Call {
	return &Bridger_GetClaimsPaged_Call{Call: _e.mock.On("GetClaimsPaged", ctx, page, pageSize, networkIDs, fromAddress)}
}

func (_c *Bridger_GetClaimsPaged_Call) Run(run func(ctx context.Context, page uint32, pageSize uint32, networkIDs []uint32, fromAddress string)) *Bridger_GetClaimsPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].([]uint32), args[4].(string))
	})
	return _c
}

func (_c *Bridger_GetClaimsPaged_Call) Return(_a0 []*bridgesync.Claim, _a1 int, _a2 error) *Bridger_GetClaimsPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Bridger_GetClaimsPaged_Call) RunAndReturn(run func(context.Context, uint32, uint32, []uint32, string) ([]*bridgesync.Claim, int, error)) *Bridger_GetClaimsPaged_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingClaimsPaged provides a mock function with given fields: ctx, page, pageSize, networkIDs, fromAddress
func (_m *Bridger) GetPendingClaimsPaged(ctx context.Context, page uint32, pageSize uint32, networkIDs []uint32, fromAddress string) ([]*bridgesync.Bridge, int, error) {
	ret := _m.Called(ctx, page, pageSize, networkIDs, fromAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingClaimsPaged")
	}

	var r0 []*bridgesync.Bridge
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, []uint32, string) ([]*bridgesync.Bridge, int, error)); ok {
		return rf(ctx, page, pageSize, networkIDs, fromAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, []uint32, string) []*bridgesync.Bridge); ok {
		r0 = rf(ctx, page, pageSize, networkIDs, fromAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bridgesync.Bridge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, []uint32, string) int); ok {
		r1 = rf(ctx, page, pageSize, networkIDs, fromAddress)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32, []uint32, string) error); ok {
		r2 = rf(ctx, page, pageSize, networkIDs, fromAddress)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Bridger_GetPendingClaimsPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingClaimsPaged'
type Bridger_GetPendingClaimsPaged_Call struct {
	*mock.Call
}

// GetPendingClaimsPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint32
//   - pageSize uint32
//   - networkIDs []uint32
//   - fromAddress string
func (_e *Bridger_Expecter) GetPendingClaimsPaged(ctx interface{}, page interface{}, pageSize interface{}, networkIDs interface{}, fromAddress interface{}) *Bridger_GetPendingClaimsPaged_Call {
	return &Bridger_GetPendingClaimsPaged_Call{Call: _e.mock.On("GetPendingClaimsPaged", ctx, page, pageSize, networkIDs, fromAddress)}
}

func (_c *Bridger_GetPendingClaimsPaged_Call) Run(run func(ctx context.Context, page uint32, pageSize uint32, networkIDs []uint32, fromAddress string)) *Bridger_GetPendingClaimsPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].([]uint32), args[4].(string))
	})
	return _c
}

func (_c *Bridger_GetPendingClaimsPaged_Call) Return(_a0 []*bridgesync.Bridge, _a1 int, _a2 error) *Bridger_GetPendingClaimsPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Bridger_GetPendingClaimsPaged_Call) RunAndReturn(run func(context.Context, uint32, uint32, []uint32, string) ([]*bridgesync.Bridge, int, error)) *Bridger_GetPendingClaimsPaged_Call {
	_c.Call.Return(run)
	return _c
}

// GetContractDepositCount provides a mock function with given fields: ctx
func (_m *Bridger) GetContractDepositCount(ctx context.Context) (uint32, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetContractDepositCount")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint32, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint32); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Bridger_GetContractDepositCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContractDepositCount'
type Bridger_GetContractDepositCount_Call struct {
	*mock.Call
}

// GetContractDepositCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Bridger_Expecter) GetContractDepositCount(ctx interface{}) *Bridger_GetContractDepositCount_Call {
	return &Bridger_GetContractDepositCount_Call{Call: _e.mock.On("GetContractDepositCount", ctx)}
}

func (_c *Bridger_GetContractDepositCount_Call) Run(run func(ctx context.Context)) *Bridger_GetContractDepositCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Bridger_GetContractDepositCount_Call) Return(_a0 uint32, _a1 error) *Bridger_GetContractDepositCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Bridger_GetContractDepositCount_Call) RunAndReturn(run func(context.Context) (uint32, error)) *Bridger_GetContractDepositCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastReorgEvent provides a mock function with given fields: ctx
func (_m *Bridger) GetLastReorgEvent(ctx context.Context) (*bridgesync.LastReorg, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastReorgEvent")
	}

	var r0 *bridgesync.LastReorg
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*bridgesync.LastReorg, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *bridgesync.LastReorg); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bridgesync.LastReorg)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Bridger_GetLastReorgEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastReorgEvent'
type Bridger_GetLastReorgEvent_Call struct {
	*mock.Call
}

// GetLastReorgEvent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Bridger_Expecter) GetLastReorgEvent(ctx interface{}) *Bridger_GetLastReorgEvent_Call {
	return &Bridger_GetLastReorgEvent_Call{Call: _e.mock.On("GetLastReorgEvent", ctx)}
}

func (_c *Bridger_GetLastReorgEvent_Call) Run(run func(ctx context.Context)) *Bridger_GetLastReorgEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Bridger_GetLastReorgEvent_Call) Return(_a0 *bridgesync.LastReorg, _a1 error) *Bridger_GetLastReorgEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Bridger_GetLastReorgEvent_Call) RunAndReturn(run func(context.Context) (*bridgesync.LastReorg, error)) *Bridger_GetLastReorgEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetLegacyTokenMigrations provides a mock function with given fields: ctx, pageNumber, pageSize
func (_m *Bridger) GetLegacyTokenMigrations(ctx context.Context, pageNumber uint32, pageSize uint32) ([]*bridgesync.LegacyTokenMigration, int, error) {
	ret := _m.Called(ctx, pageNumber, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetLegacyTokenMigrations")
	}

	var r0 []*bridgesync.LegacyTokenMigration
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) ([]*bridgesync.LegacyTokenMigration, int, error)); ok {
		return rf(ctx, pageNumber, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) []*bridgesync.LegacyTokenMigration); ok {
		r0 = rf(ctx, pageNumber, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bridgesync.LegacyTokenMigration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32) int); ok {
		r1 = rf(ctx, pageNumber, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32) error); ok {
		r2 = rf(ctx, pageNumber, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Bridger_GetLegacyTokenMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLegacyTokenMigrations'
type Bridger_GetLegacyTokenMigrations_Call struct {
	*mock.Call
}

// GetLegacyTokenMigrations is a helper method to define mock.On call
//   - ctx context.Context
//   - pageNumber uint32
//   - pageSize uint32
func (_e *Bridger_Expecter) GetLegacyTokenMigrations(ctx interface{}, pageNumber interface{}, pageSize interface{}) *Bridger_GetLegacyTokenMigrations_Call {
	return &Bridger_GetLegacyTokenMigrations_Call{Call: _e.mock.On("GetLegacyTokenMigrations", ctx, pageNumber, pageSize)}
}

func (_c *Bridger_GetLegacyTokenMigrations_Call) Run(run func(ctx context.Context, pageNumber uint32, pageSize uint32)) *Bridger_GetLegacyTokenMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32))
	})
	return _c
}

func (_c *Bridger_GetLegacyTokenMigrations_Call) Return(_a0 []*bridgesync.LegacyTokenMigration, _a1 int, _a2 error) *Bridger_GetLegacyTokenMigrations_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Bridger_GetLegacyTokenMigrations_Call) RunAndReturn(run func(context.Context, uint32, uint32) ([]*bridgesync.LegacyTokenMigration, int, error)) *Bridger_GetLegacyTokenMigrations_Call {
	_c.Call.Return(run)
	return _c
}

// GetProof provides a mock function with given fields: ctx, depositCount, localExitRoot
func (_m *Bridger) GetProof(ctx context.Context, depositCount uint32, localExitRoot common.Hash) (types.Proof, error) {
	ret := _m.Called(ctx, depositCount, localExitRoot)

	if len(ret) == 0 {
		panic("no return value specified for GetProof")
	}

	var r0 types.Proof
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, common.Hash) (types.Proof, error)); ok {
		return rf(ctx, depositCount, localExitRoot)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, common.Hash) types.Proof); ok {
		r0 = rf(ctx, depositCount, localExitRoot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Proof)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, common.Hash) error); ok {
		r1 = rf(ctx, depositCount, localExitRoot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Bridger_GetProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProof'
type Bridger_GetProof_Call struct {
	*mock.Call
}

// GetProof is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCount uint32
//   - localExitRoot common.Hash
func (_e *Bridger_Expecter) GetProof(ctx interface{}, depositCount interface{}, localExitRoot interface{}) *Bridger_GetProof_Call {
	return &Bridger_GetProof_Call{Call: _e.mock.On("GetProof", ctx, depositCount, localExitRoot)}
}

func (_c *Bridger_GetProof_Call) Run(run func(ctx context.Context, depositCount uint32, localExitRoot common.Hash)) *Bridger_GetProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(common.Hash))
	})
	return _c
}

func (_c *Bridger_GetProof_Call) Return(_a0 types.Proof, _a1 error) *Bridger_GetProof_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Bridger_GetProof_Call) RunAndReturn(run func(context.Context, uint32, common.Hash) (types.Proof, error)) *Bridger_GetProof_Call {
	_c.Call.Return(run)
	return _c
}

// GetRootByLER provides a mock function with given fields: ctx, ler
func (_m *Bridger) GetRootByLER(ctx context.Context, ler common.Hash) (*types.Root, error) {
	ret := _m.Called(ctx, ler)

	if len(ret) == 0 {
		panic("no return value specified for GetRootByLER")
	}

	var r0 *types.Root
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) (*types.Root, error)); ok {
		return rf(ctx, ler)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) *types.Root); ok {
		r0 = rf(ctx, ler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Root)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = rf(ctx, ler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Bridger_GetRootByLER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootByLER'
type Bridger_GetRootByLER_Call struct {
	*mock.Call
}

// GetRootByLER is a helper method to define mock.On call
//   - ctx context.Context
//   - ler common.Hash
func (_e *Bridger_Expecter) GetRootByLER(ctx interface{}, ler interface{}) *Bridger_GetRootByLER_Call {
	return &Bridger_GetRootByLER_Call{Call: _e.mock.On("GetRootByLER", ctx, ler)}
}

func (_c *Bridger_GetRootByLER_Call) Run(run func(ctx context.Context, ler common.Hash)) *Bridger_GetRootByLER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash))
	})
	return _c
}

func (_c *Bridger_GetRootByLER_Call) Return(_a0 *types.Root, _a1 error) *Bridger_GetRootByLER_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Bridger_GetRootByLER_Call) RunAndReturn(run func(context.Context, common.Hash) (*types.Root, error)) *Bridger_GetRootByLER_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenMappings provides a mock function with given fields: ctx, pageNumber, pageSize
func (_m *Bridger) GetTokenMappings(ctx context.Context, pageNumber uint32, pageSize uint32) ([]*bridgesync.TokenMapping, int, error) {
	ret := _m.Called(ctx, pageNumber, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenMappings")
	}

	var r0 []*bridgesync.TokenMapping
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) ([]*bridgesync.TokenMapping, int, error)); ok {
		return rf(ctx, pageNumber, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) []*bridgesync.TokenMapping); ok {
		r0 = rf(ctx, pageNumber, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bridgesync.TokenMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32) int); ok {
		r1 = rf(ctx, pageNumber, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32) error); ok {
		r2 = rf(ctx, pageNumber, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Bridger_GetTokenMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenMappings'
type Bridger_GetTokenMappings_Call struct {
	*mock.Call
}

// GetTokenMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - pageNumber uint32
//   - pageSize uint32
func (_e *Bridger_Expecter) GetTokenMappings(ctx interface{}, pageNumber interface{}, pageSize interface{}) *Bridger_GetTokenMappings_Call {
	return &Bridger_GetTokenMappings_Call{Call: _e.mock.On("GetTokenMappings", ctx, pageNumber, pageSize)}
}

func (_c *Bridger_GetTokenMappings_Call) Run(run func(ctx context.Context, pageNumber uint32, pageSize uint32)) *Bridger_GetTokenMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32))
	})
	return _c
}

func (_c *Bridger_GetTokenMappings_Call) Return(_a0 []*bridgesync.TokenMapping, _a1 int, _a2 error) *Bridger_GetTokenMappings_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Bridger_GetTokenMappings_Call) RunAndReturn(run func(context.Context, uint32, uint32) ([]*bridgesync.TokenMapping, int, error)) *Bridger_GetTokenMappings_Call {
	_c.Call.Return(run)
	return _c
}

// NewBridger creates a new instance of Bridger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBridger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bridger {
	mock := &Bridger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
